server:
  port: 10105

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:10101}/eureka/

#turbine:
#  aggregator:
#    clusterConfig: default
#  appConfig: physical-person-meta  # 配置Eureka中的serviceId列表，表明监控哪些服务
#  clusterNameExpression: new String("default")

spring:
  application:
    name: turbine
  zipkin:
    base-url: localhost:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0 #采样比例
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    virtual-host: /
  #stream绑定
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${spring.rabbitmq.host}
                port: ${spring.rabbitmq.port}
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                virtual-host: ${spring.rabbitmq.virtual-host}
      default-binder: rabbit

management:
  endpoints:
    web:
      exposure:
        include: '*'
  #关闭hystrix.stream端点
  endpoint:
    hystrix:
      stream:
        enabled: false
#turbine配置
turbine:
  # 聚合的服务流
  app-config: physical-book-meta,physical-person-meta
  # 表明Turbine会收集名为default的集群中的所有聚合流
  cluster-name-expression: "'default'"

logging:
  level:
    org.springframework.web: debug

